Add source code for Chapter 14
Apress/beginning-cpp20 pull request #15
Opened 2020-10-17 12:28 UTC by Peter-VanWeert

2020-10-18 17:09 UTC, MarcGregoire requested changes

2020-10-18 17:09 UTC, MarcGregoire commented on Exercises/NoModules/Chapter 14/Soln14_01/Animals.cpp
> +  std::cout << "My name is " << m_name << " and I weigh " << m_weight << "lbs." << std::endl;
format?

2020-10-18 17:09 UTC, MarcGregoire commented on Exercises/NoModules/Chapter 14/Soln14_04/Person.cpp
> +  std::cout << "\nThis is " << m_name << " who is " << m_age << " years old." << std::endl;
format?

2020-10-18 17:09 UTC, MarcGregoire commented on Exercises/NoModules/Chapter 14/Soln14_04/Person.cpp
> +  // Unreacheble return statement required by some compilers
Unreachable

2020-10-24 11:45 UTC, Peter-VanWeert commented on Examples/NoModules/Chapter 14/Ex14_01/Ex14_01A.cpp
> +// Changing the access specification of inherited members
Yeah, Ex14_01 and Ex14_01A seem to have been somewhat mixed...

2020-10-24 11:45 UTC, Peter-VanWeert commented on Examples/NoModules/Chapter 14/Ex14_01/Carton.h
> +class Carton : private Box
Yeah, Ex14_01 and Ex14_01A seem to have been somewhat mixed...

2020-10-24 11:45 UTC, Peter-VanWeert commented on Examples/NoModules/Chapter 14/Ex14_01/Ex14_01A.cpp
> +  // std::cout << "chocolateCarton length is " << chocolateCarton.getLength() << std::endl;
Yeah, Ex14_01 and Ex14_01A seem to have been somewhat mixed...

2020-10-24 11:45 UTC, Peter-VanWeert commented on Examples/NoModules/Chapter 14/Ex14_01A/Box.h
> +  double height {1.0};
Old code...

2020-10-24 11:46 UTC, Peter-VanWeert commented on Examples/NoModules/Chapter 14/Ex14_01A/Box.h
> +  Box() = default;                          // No-arg constructor
Yeah, Ex14_01 and Ex14_01A seem to have been somewhat mixed into the Ex14_01 folder, and the Ex14_01A one is just old code...

2020-10-24 11:47 UTC, Peter-VanWeert commented on Examples/NoModules/Chapter 14/Ex14_01A/Box.h
> +#include <iomanip>                          // For stream manipulators
Yeah, Ex14_01A is just a folder with old code...

2020-10-24 11:57 UTC, Peter-VanWeert commented on Examples/NoModules/Chapter 14/Ex14_01A/Box.h
> +  friend std::ostream& operator<<(std::ostream& stream, const Box& box);
Old code...

2020-10-24 11:58 UTC, Peter-VanWeert commented on Examples/NoModules/Chapter 14/Ex14_02/Box.h
> +inline std::ostream& operator<<(std::ostream& stream, const Box& box)
Yeah, I also noticed. It's on my list of errata...

2020-10-24 11:58 UTC, Peter-VanWeert commented on Examples/NoModules/Chapter 14/Ex14_01A/Box.h
> +    << std::setw(2) << box.length << ','
Not really...

2020-10-24 11:59 UTC, Peter-VanWeert commented on Examples/NoModules/Chapter 14/Ex14_01A/Carton.h
> +  std::string material;
Old code...

2020-10-24 12:01 UTC, Peter-VanWeert commented on Examples/NoModules/Chapter 14/Ex14_03/Carton.h
> +  // Copy constructor (wrong)
The text starts with the wrong version, which it explicitly states won't work. Idea is that the reader can verify the (wrong) output, then fix it as instructed in the text, and then verify again.

2020-10-24 12:03 UTC, Peter-VanWeert commented on Examples/NoModules/Chapter 14/Ex14_07/FoodContainer.h
> +protected:  // Protected to make initialization in Carton constructor word (book says private)
Yup

2020-10-24 12:04 UTC, Peter-VanWeert commented on Examples/NoModules/Chapter 14/Ex14_07A/FoodContainer.h
> +protected:  // Protected to make initialization in Carton constructor word (book says private)
Yup. And I also meant work, not word.

2020-10-24 12:05 UTC, Peter-VanWeert commented on Exercises/NoModules/Chapter 14/Soln14_01/Animals.cpp
> +  std::cout << "My name is " << m_name << " and I weigh " << m_weight << "lbs." << std::endl;
Meh...

2020-10-24 12:07 UTC, merged