Add source code for Chapter 18
Apress/beginning-cpp20 pull request #19
Opened 2020-10-18 16:29 UTC by Peter-VanWeert

2020-10-19 10:35 UTC, MarcGregoire requested changes
Note: I mentioned the use of std::exchange() on a couple of places.
You can ignore that. I see that you introduce std::exchange() in the very last exercises in this chapter.

2020-10-19 10:35 UTC, MarcGregoire commented on Exercises/NoModules/Chapter 18/Soln18_03/Customer.cpp
> +  , m_city(city)
uniform init

2020-10-19 10:35 UTC, MarcGregoire commented on Exercises/NoModules/Chapter 18/Soln18_03/Customer.cpp
> +  return result;
Actually, format would be ideal here no?
Also in other solutions.

2020-10-19 10:35 UTC, MarcGregoire commented on Exercises/NoModules/Chapter 18/Soln18_03/DB.cpp
> +// A mocked database
check the comments I had in the other chapter.
Also for all the other files in this folder.

2020-10-19 10:35 UTC, MarcGregoire commented on Exercises/NoModules/Chapter 18/Soln18_04/Customer.cpp
> +// A simple C++ customer class
Check with previous comments for all these files.

2020-10-19 10:35 UTC, MarcGregoire commented on Exercises/NoModules/Chapter 18/Soln18_04/DB_RAII.h
> +    : m_connection(other.m_connection)
uniform init

2020-10-19 10:35 UTC, MarcGregoire commented on Exercises/NoModules/Chapter 18/Soln18_05/Customer.cpp
> +// A simple C++ customer class
Check previous comments for all these files.

2020-10-19 10:35 UTC, MarcGregoire commented on Exercises/NoModules/Chapter 18/Soln18_05/DB_RAII.h
> +    : m_connection(std::exchange(other.m_connection, nullptr))
uniform init

2020-10-25 14:15 UTC, Peter-VanWeert commented on Exercises/NoModules/Chapter 18/Soln18_01/Box.h
> +  friend std::ostream& operator<<(std::ostream& out, const Box& box)
Nope. This one was a friend.

2020-10-25 14:16 UTC, Peter-VanWeert commented on Exercises/NoModules/Chapter 18/Soln18_02/LinkedList.h
> +Do not forget to the Node constructor to prevent any unnecessary copies there!
I forgot?

2020-10-29 09:04 UTC, Peter-VanWeert commented on Exercises/NoModules/Chapter 18/Soln18_02/LinkedList.h
> +  void push_back(T&& value);               // Move an object to the tail
Intro was outdated. Updated now.

2020-10-29 09:32 UTC, merged