Add exercise solutions for Chapter 20
Apress/beginning-cpp20 pull request #23
Opened 2020-11-01 10:05 UTC by Peter-VanWeert

2020-11-01 13:08 UTC, MarcGregoire requested changes

2020-11-01 13:08 UTC, MarcGregoire commented on Exercises/NoModules/Chapter 20/Soln20_14/Soln20_14.cpp
> +           iota(2u, std::max(2u, static_cast<unsigned>(std::sqrt(number)))),
Otherwise:
```
3
Yes, that is a prime!
4
Yes, that is a prime!
```

2020-11-01 13:08 UTC, MarcGregoire commented on Exercises/NoModules/Chapter 20/Soln20_14/Soln20_14.cpp
> +  auto view = std::ranges::istream_view<int>(std::cin)
uniform init
Also few times below.

2020-11-01 13:08 UTC, MarcGregoire commented on Exercises/NoModules/Chapter 20/Soln20_14/Soln20_14.cpp
> +           iota(2u, std::max(2u, static_cast<unsigned>(std::sqrt(number)))),
When adding +1, I get:
```
0
1
2
3
Yes, that is a prime!
4
5
Yes, that is a prime!
6
7
Yes, that is a prime!
```
Which is also not entirely correct, as 2 is prime.

2020-11-01 13:08 UTC, MarcGregoire commented on Exercises/NoModules/Chapter 20/Soln20_14/Soln20_14.cpp
> +           iota(2u, std::max(2u, static_cast<unsigned>(std::sqrt(number)))),
Same comment for previous exercises with an isPrime() function. Verify all of them and maybe make all of them identical.

2020-11-07 10:52 UTC, Peter-VanWeert commented on Exercises/NoModules/Chapter 20/Soln20_03/Soln20_03.cpp
> +  // A list in the SparseArray is selected by the index in letters of the first letter in a word.
Worse: it even says it's using the index in letters etc...

2020-11-07 11:05 UTC, Peter-VanWeert commented on Exercises/NoModules/Chapter 20/Soln20_03A/Soln20_03A.cpp
> +    const auto [begin, end] = lists.equal_range(letter);
Last minute changes...

2020-11-07 11:06 UTC, Peter-VanWeert commented on Exercises/NoModules/Chapter 20/Soln20_03A/Soln20_03A.cpp
> +      if (!(++count % perline))
Noticed how all these loops were wrong ;-)

2020-11-07 11:07 UTC, Peter-VanWeert commented on Exercises/NoModules/Chapter 20/Soln20_03A/Soln20_03A.cpp
> +      previous_letter = letter;
@MarcGregoire: this one was even more wrong than the others...

2020-11-07 12:00 UTC, merged