Add solutions to exercises of Appendix A
Apress/beginning-cpp20 pull request #27
Opened 2020-11-08 17:07 UTC by Peter-VanWeert

2020-11-13 18:07 UTC, MarcGregoire requested changes

2020-11-13 18:07 UTC, MarcGregoire commented on Exercises/NoModules/Appendix A/SolnA_04/SolnA_04.cpp
> +    SmartException exception{ "Throwing later...", {} };
technically, you don't have to specify the empty {} right.

2020-11-13 18:07 UTC, MarcGregoire commented on Exercises/NoModules/Appendix A/SolnA_05/PrintThis.h
> +// but convention dictates you add the regardless.
"them"

2020-11-13 18:07 UTC, MarcGregoire commented on Exercises/NoModules/Appendix A/SolnA_05/PrintThat.h
> +// but convention dictates you add the regardless.
"them"

2020-11-13 18:07 UTC, MarcGregoire commented on Exercises/NoModules/Appendix A/SolnA_06/PrintThat.h
> +// but convention dictates you add the regardless.
"them"

2020-11-13 18:07 UTC, MarcGregoire commented on Exercises/NoModules/Appendix A/SolnA_06/PrintThis.h
> +// but convention dictates you add the regardless.
"them"

2020-11-13 18:07 UTC, MarcGregoire commented on Exercises/NoModules/Appendix A/SolnA_07A/PrintThis.h
> +// but convention dictates you add the regardless.
"them"

2020-11-13 18:07 UTC, MarcGregoire commented on Exercises/NoModules/Appendix A/SolnA_07A/PrintThat.h
> +// but convention dictates you add the regardless.
"them"

2020-11-13 18:07 UTC, MarcGregoire commented on Exercises/NoModules/Appendix A/SolnA_07B/PrintThis.h
> +// but convention dictates you add the regardless.
"them"

2020-11-13 18:07 UTC, MarcGregoire commented on Exercises/NoModules/Appendix A/SolnA_07B/PrintThat.h
> +// but convention dictates you add the regardless.
"them"

2020-11-13 18:07 UTC, MarcGregoire commented on Exercises/NoModules/Appendix A/SolnA_07B/Print.h
> +inline int count = 0;
uniform init

2020-11-14 09:25 UTC, Peter-VanWeert commented on Exercises/NoModules/Appendix A/SolnA_03/SmartException.cpp
> +  throw* this;
You mean the position of the *, right? Yup, very weird.

2020-11-14 09:27 UTC, Peter-VanWeert commented on Exercises/NoModules/Appendix A/SolnA_03/SolnA_03.cpp
> +    SmartException exception{ "Throwing later...", {} };
True. It's an optional performance optimisation. I commented on this in the member specification in the header. Added similar comment here as well.

2020-11-14 09:36 UTC, merged

2020-11-14 10:26 UTC, MarcGregoire commented on Exercises/NoModules/Appendix A/SolnA_03/SmartException.cpp
> +  throw* this;
yes, i would write "throw *this", not "throw* this"