Chapter 13: modular version
Apress/beginning-cpp20 pull request #29
Opened 2020-11-15 11:57 UTC by Peter-VanWeert

2020-11-20 18:47 UTC, MarcGregoire requested changes

2020-11-20 18:47 UTC, MarcGregoire commented on Examples/Modules/Chapter 13/Ex13_06/Box.cpp
> +#include <cmath>    // For the min() and max() function templates
I would move this include to the global module fragment.

2020-11-20 18:48 UTC, MarcGregoire commented
Mmm, I didn't have many comments here ... only one :-D
Though, as discussed on Messenger, I did not compile everything, no time for that at this moment.
I just took 2 or 3 and tried to compiler them.

2020-11-22 14:02 UTC, Peter-VanWeert commented
> 
> 
> Mmm, I didn't have many comments here ... only one :-D
> Though, as discussed on Messenger, I did not compile everything, no time for that at this moment.
> I just took 2 or 3 and tried to compiler them.

Should  be ok. I compilered them all normally (for as far as that's possible...).

2020-11-22 14:02 UTC, merged